name: 'MPTCP Upstream Build Export Action'
description: 'Build any changes on the "export" branch'
inputs:
  each_commit:
    description: 'Set it to true to validate the compilation of each commit'
    required: false
    default: 'true'
  ccache_maxsize:
    description: 'Set the maximum size for CCache in {{ github.workspace }}/.ccache dir'
    required: false
    default: '5G'
  defconfig:
    description: 'Defconfig to load (x86_64 or i386)'
    required: false
    default: 'x86_64'
  ipv6:
    description: 'With or without IPv6 kconfig?'
    required: false
    default: 'with_ipv6'
  mptcp:
    description: 'With or without MPTCP kconfig?'
    required: false
    default: 'with_mptcp'
  base:
    description: 'Validate each commit from the bottom or from the top'
    required: false
    default: 'bottom'

runs:
  using: 'docker'
  image: 'Dockerfile'
